on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: eni1998/python-helloworld:latest

      - name: Save Docker Buildx Outputs
        env:
          BUILDX_OUTPUT: ${{ steps.build.outputs.digest }}
        run: echo "::set-env name=BUILDX_OUTPUT::${BUILDX_OUTPUT}"

      - name: Save Docker Buildx Outputs to File
        env:
          BUILDX_OUTPUT: ${{ steps.build.outputs.digest }}
        run: echo "BUILDX_OUTPUT=${BUILDX_OUTPUT}" >> $GITHUB_ENV

      - name: Set up DockerHub PAT
        run: echo "${{ secrets.DOCKERHUB_PAT }}" >> $GITHUB_ENV

      - name: Login to DockerHub with PAT
        run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u eni1998 --password-stdin


      - name: Set up DockerHub PAT
        run: echo "${{ secrets.DOCKERHUB_PAT }}" >> $GITHUB_ENV

      - name: Login to DockerHub with PAT
        run: echo "${{ secrets.DOCKERHUB_PAT }}" | docker login -u eni1998 --password-stdin

    

